package com.wash.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("calendar", "id", Calendar.class);
		arp.addMapping("category", "id", Category.class);
		arp.addMapping("dk_audit_record", "id", DkAuditRecord.class);
		arp.addMapping("dk_contract", "id", DkContract.class);
		arp.addMapping("dk_contract_pay", "id", DkContractPay.class);
		arp.addMapping("dk_contract_product", "id", DkContractProduct.class);
		arp.addMapping("dk_contract_schedule", "id", DkContractSchedule.class);
		arp.addMapping("dk_member", "id", DkMember.class);
		arp.addMapping("dk_product", "id", DkProduct.class);
		arp.addMapping("dk_product_stock_record", "id", DkProductStockRecord.class);
		arp.addMapping("dk_quotation", "id", DkQuotation.class);
		arp.addMapping("dk_quotation_product", "id", DkQuotationProduct.class);
		arp.addMapping("dk_worker", "id", DkWorker.class);
		arp.addMapping("form_leave", "id", FormLeave.class);
		arp.addMapping("gen_scheme", "id", GenScheme.class);
		arp.addMapping("gen_table", "id", GenTable.class);
		arp.addMapping("gen_table_column", "id", GenTableColumn.class);
		arp.addMapping("gen_template", "id", GenTemplate.class);
		arp.addMapping("goods", "id", Goods.class);
		arp.addMapping("group_user", "id", GroupUser.class);
		arp.addMapping("iim_chat_history", "id", IimChatHistory.class);
		arp.addMapping("iim_mail", "id", IimMail.class);
		arp.addMapping("iim_mail_box", "id", IimMailBox.class);
		arp.addMapping("iim_mail_compose", "id", IimMailCompose.class);
		arp.addMapping("monitor", "id", Monitor.class);
		arp.addMapping("oa_notify", "id", OaNotify.class);
		arp.addMapping("oa_notify_record", "id", OaNotifyRecord.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("sys_area", "id", SysArea.class);
		arp.addMapping("sys_dict", "id", SysDict.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_mdict", "id", SysMdict.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_office", "id", SysOffice.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		// Composite Primary Key order: menu_id,role_id
		arp.addMapping("sys_role_menu", "menu_id,role_id", SysRoleMenu.class);
		// Composite Primary Key order: office_id,role_id
		arp.addMapping("sys_role_office", "office_id,role_id", SysRoleOffice.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("sys_user_friend", "id", SysUserFriend.class);
		// Composite Primary Key order: role_id,user_id
		arp.addMapping("sys_user_role", "role_id,user_id", SysUserRole.class);
		arp.addMapping("systemconfig", "id", Systemconfig.class);
		arp.addMapping("t_group", "id", Group.class);
		arp.addMapping("test_data", "id", TestData.class);
		arp.addMapping("test_data_child", "id", TestDataChild.class);
		arp.addMapping("test_data_child2", "id", TestDataChild2.class);
		arp.addMapping("test_data_child3", "id", TestDataChild3.class);
		arp.addMapping("test_data_main", "id", TestDataMain.class);
		arp.addMapping("test_interface", "id", TestInterface.class);
		arp.addMapping("test_line_weather_main_city", "id", TestLineWeatherMainCity.class);
		arp.addMapping("test_pie_class", "id", TestPieClass.class);
		arp.addMapping("test_tree", "id", TestTree.class);
		arp.addMapping("testnote", "id", Testnote.class);
		arp.addMapping("wash_car_member", "id", WashCarMember.class);
		arp.addMapping("wash_device", "id", WashDevice.class);
		arp.addMapping("wash_device_fault", "id", WashDeviceFault.class);
		arp.addMapping("wash_device_heart", "id", WashDeviceHeart.class);
		arp.addMapping("wash_device_record", "id", WashDeviceRecord.class);
		arp.addMapping("wash_member", "id", WashMember.class);
		arp.addMapping("wash_ord_evaluate", "id", WashOrdEvaluate.class);
		arp.addMapping("wash_ord_order", "id", WashOrdOrder.class);
		arp.addMapping("wash_ord_set_meal", "id", WashOrdSetMeal.class);
		arp.addMapping("wash_set_meal", "id", WashSetMeal.class);
		arp.addMapping("wash_work_device_record", "id", WashWorkDeviceRecord.class);
		arp.addMapping("wash_work_person", "id", WashWorkPerson.class);
	}
}

