package com.wash.model;

import com.wash.model.base.BaseCalendar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Calendar extends BaseCalendar<Calendar> {
	public static final Calendar dao = new Calendar().dao();
}
