package com.wash.model;

import com.wash.model.base.BaseDkAuditRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkAuditRecord extends BaseDkAuditRecord<DkAuditRecord> {
	public static final DkAuditRecord dao = new DkAuditRecord().dao();
}
