package com.wash.model;

import com.wash.model.base.BaseDkContractProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkContractProduct extends BaseDkContractProduct<DkContractProduct> {
	public static final DkContractProduct dao = new DkContractProduct().dao();
}
