package com.wash.model;

import com.wash.model.base.BaseDkContractPay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkContractPay extends BaseDkContractPay<DkContractPay> {
	public static final DkContractPay dao = new DkContractPay().dao();
}
