package com.wash.model;

import com.wash.model.base.BaseDkContractSchedule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkContractSchedule extends BaseDkContractSchedule<DkContractSchedule> {
	public static final DkContractSchedule dao = new DkContractSchedule().dao();
}
