package com.wash.model;

import com.wash.model.base.BaseDkContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkContract extends BaseDkContract<DkContract> {
	public static final DkContract dao = new DkContract().dao();
}
