package com.wash.model;

import com.wash.model.base.BaseDkMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkMember extends BaseDkMember<DkMember> {
	public static final DkMember dao = new DkMember().dao();
}
