package com.wash.model;

import com.wash.model.base.BaseDkProductStockRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkProductStockRecord extends BaseDkProductStockRecord<DkProductStockRecord> {
	public static final DkProductStockRecord dao = new DkProductStockRecord().dao();
}
