package com.wash.model;

import com.wash.model.base.BaseDkProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkProduct extends BaseDkProduct<DkProduct> {
	public static final DkProduct dao = new DkProduct().dao();
}
