package com.wash.model;

import com.wash.model.base.BaseDkQuotation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkQuotation extends BaseDkQuotation<DkQuotation> {
	public static final DkQuotation dao = new DkQuotation().dao();
}
