package com.wash.model;

import com.wash.model.base.BaseDkQuotationProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkQuotationProduct extends BaseDkQuotationProduct<DkQuotationProduct> {
	public static final DkQuotationProduct dao = new DkQuotationProduct().dao();
}
