package com.wash.model;

import com.wash.model.base.BaseDkWorker;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DkWorker extends BaseDkWorker<DkWorker> {
	public static final DkWorker dao = new DkWorker().dao();
}
