package com.wash.model;

import com.wash.model.base.BaseFormLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FormLeave extends BaseFormLeave<FormLeave> {
	public static final FormLeave dao = new FormLeave().dao();
}
