package com.wash.model;

import com.wash.model.base.BaseGenScheme;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenScheme extends BaseGenScheme<GenScheme> {
	public static final GenScheme dao = new GenScheme().dao();
}
