package com.wash.model;

import com.wash.model.base.BaseGenTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenTemplate extends BaseGenTemplate<GenTemplate> {
	public static final GenTemplate dao = new GenTemplate().dao();
}
