package com.wash.model;

import com.wash.model.base.BaseGenTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenTable extends BaseGenTable<GenTable> {
	public static final GenTable dao = new GenTable().dao();
}
