package com.wash.model;

import com.wash.model.base.BaseGenTableColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GenTableColumn extends BaseGenTableColumn<GenTableColumn> {
	public static final GenTableColumn dao = new GenTableColumn().dao();
}
