package com.wash.model;

import com.wash.model.base.BaseGroupUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupUser extends BaseGroupUser<GroupUser> {
	public static final GroupUser dao = new GroupUser().dao();
}
