package com.wash.model;

import com.wash.model.base.BaseGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Group extends BaseGroup<Group> {
	public static final Group dao = new Group().dao();
}
