package com.wash.model;

import com.wash.model.base.BaseIimChatHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IimChatHistory extends BaseIimChatHistory<IimChatHistory> {
	public static final IimChatHistory dao = new IimChatHistory().dao();
}
