package com.wash.model;

import com.wash.model.base.BaseIimMailBox;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IimMailBox extends BaseIimMailBox<IimMailBox> {
	public static final IimMailBox dao = new IimMailBox().dao();
}
