package com.wash.model;

import com.wash.model.base.BaseIimMailCompose;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IimMailCompose extends BaseIimMailCompose<IimMailCompose> {
	public static final IimMailCompose dao = new IimMailCompose().dao();
}
