package com.wash.model;

import com.wash.model.base.BaseIimMail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IimMail extends BaseIimMail<IimMail> {
	public static final IimMail dao = new IimMail().dao();
}
