package com.wash.model;

import com.wash.model.base.BaseMonitor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Monitor extends BaseMonitor<Monitor> {
	public static final Monitor dao = new Monitor().dao();
}
