package com.wash.model;

import com.wash.model.base.BaseOaNotify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaNotify extends BaseOaNotify<OaNotify> {
	public static final OaNotify dao = new OaNotify().dao();
}
