package com.wash.model;

import com.wash.model.base.BaseOaNotifyRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OaNotifyRecord extends BaseOaNotifyRecord<OaNotifyRecord> {
	public static final OaNotifyRecord dao = new OaNotifyRecord().dao();
}
