package com.wash.model;

import com.wash.model.base.BaseSysArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysArea extends BaseSysArea<SysArea> {
	public static final SysArea dao = new SysArea().dao();
}
