package com.wash.model;

import com.wash.model.base.BaseSysMdict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysMdict extends BaseSysMdict<SysMdict> {
	public static final SysMdict dao = new SysMdict().dao();
}
