package com.wash.model;

import com.wash.model.base.BaseSysOffice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysOffice extends BaseSysOffice<SysOffice> {
	public static final SysOffice dao = new SysOffice().dao();
}
