package com.wash.model;

import com.wash.model.base.BaseSysRoleOffice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleOffice extends BaseSysRoleOffice<SysRoleOffice> {
	public static final SysRoleOffice dao = new SysRoleOffice().dao();
}
