package com.wash.model;

import com.wash.model.base.BaseSystemconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Systemconfig extends BaseSystemconfig<Systemconfig> {
	public static final Systemconfig dao = new Systemconfig().dao();
}
