package com.wash.model;

import com.wash.model.base.BaseSysUserFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserFriend extends BaseSysUserFriend<SysUserFriend> {
	public static final SysUserFriend dao = new SysUserFriend().dao();
}
