package com.wash.model;

import com.wash.model.base.BaseTestDataChild3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDataChild3 extends BaseTestDataChild3<TestDataChild3> {
	public static final TestDataChild3 dao = new TestDataChild3().dao();
}
