package com.wash.model;

import com.wash.model.base.BaseTestData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestData extends BaseTestData<TestData> {
	public static final TestData dao = new TestData().dao();
}
