package com.wash.model;

import com.wash.model.base.BaseTestTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestTree extends BaseTestTree<TestTree> {
	public static final TestTree dao = new TestTree().dao();
}
