package com.wash.model;

import com.wash.model.base.BaseTestPieClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestPieClass extends BaseTestPieClass<TestPieClass> {
	public static final TestPieClass dao = new TestPieClass().dao();
}
