package com.wash.model;

import com.wash.model.base.BaseTestDataChild2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDataChild2 extends BaseTestDataChild2<TestDataChild2> {
	public static final TestDataChild2 dao = new TestDataChild2().dao();
}
