package com.wash.model;

import com.wash.model.base.BaseTestInterface;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestInterface extends BaseTestInterface<TestInterface> {
	public static final TestInterface dao = new TestInterface().dao();
}
