package com.wash.model;

import com.wash.model.base.BaseTestDataMain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDataMain extends BaseTestDataMain<TestDataMain> {
	public static final TestDataMain dao = new TestDataMain().dao();
}
