package com.wash.model;

import com.wash.model.base.BaseTestLineWeatherMainCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestLineWeatherMainCity extends BaseTestLineWeatherMainCity<TestLineWeatherMainCity> {
	public static final TestLineWeatherMainCity dao = new TestLineWeatherMainCity().dao();
}
