package com.wash.model;

import com.wash.model.base.BaseTestnote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Testnote extends BaseTestnote<Testnote> {
	public static final Testnote dao = new Testnote().dao();
}
