package com.wash.model;

import com.wash.model.base.BaseTestDataChild;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestDataChild extends BaseTestDataChild<TestDataChild> {
	public static final TestDataChild dao = new TestDataChild().dao();
}
