package com.wash.model;

import com.wash.model.base.BaseWashWorkPerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashWorkPerson extends BaseWashWorkPerson<WashWorkPerson> {
	public static final WashWorkPerson dao = new WashWorkPerson().dao();
}
