package com.wash.model;

import com.wash.model.base.BaseWashDeviceRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashDeviceRecord extends BaseWashDeviceRecord<WashDeviceRecord> {
	public static final WashDeviceRecord dao = new WashDeviceRecord().dao();
}
