package com.wash.model;

import com.wash.model.base.BaseWashTFlow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashTFlow extends BaseWashTFlow<WashTFlow> {
	public static final WashTFlow dao = new WashTFlow().dao();
}
