package com.wash.model;

import com.wash.model.base.BaseWashOrdSetMeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashOrdSetMeal extends BaseWashOrdSetMeal<WashOrdSetMeal> {
	public static final WashOrdSetMeal dao = new WashOrdSetMeal().dao();
}
