package com.wash.model;

import com.wash.model.base.BaseWashOrdOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashOrdOrder extends BaseWashOrdOrder<WashOrdOrder> {
	public static final WashOrdOrder dao = new WashOrdOrder().dao();
}
