package com.wash.model;

import com.wash.model.base.BaseWashDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashDevice extends BaseWashDevice<WashDevice> {
	public static final WashDevice dao = new WashDevice().dao();
}
