package com.wash.model;

import com.wash.model.base.BaseWashOrdEvaluate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashOrdEvaluate extends BaseWashOrdEvaluate<WashOrdEvaluate> {
	public static final WashOrdEvaluate dao = new WashOrdEvaluate().dao();
}
