package com.wash.model;

import com.wash.model.base.BaseWashSetMeal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashSetMeal extends BaseWashSetMeal<WashSetMeal> {
	public static final WashSetMeal dao = new WashSetMeal().dao();
}
