package com.wash.model;

import com.wash.model.base.BaseWashMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashMember extends BaseWashMember<WashMember> {
	public static final WashMember dao = new WashMember().dao();
}
