package com.wash.model;

import com.wash.model.base.BaseWashDeviceHeart;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashDeviceHeart extends BaseWashDeviceHeart<WashDeviceHeart> {
	public static final WashDeviceHeart dao = new WashDeviceHeart().dao();
}
