package com.wash.model;

import com.wash.model.base.BaseWashCompanyPurse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashCompanyPurse extends BaseWashCompanyPurse<WashCompanyPurse> {
	public static final WashCompanyPurse dao = new WashCompanyPurse().dao();
}
