package com.wash.model;

import com.wash.model.base.BaseWashPlateNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashPlateNumber extends BaseWashPlateNumber<WashPlateNumber> {
	public static final WashPlateNumber dao = new WashPlateNumber().dao();
}
