package com.wash.model;

import com.wash.model.base.BaseWashTbSequence;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashTbSequence extends BaseWashTbSequence<WashTbSequence> {
	public static final WashTbSequence dao = new WashTbSequence().dao();
}
