package com.wash.model;

import com.wash.model.base.BaseWashCouponDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashCouponDetail extends BaseWashCouponDetail<WashCouponDetail> {
	public static final WashCouponDetail dao = new WashCouponDetail().dao();
}
