package com.wash.model;

import com.wash.model.base.BaseWashDeviceFault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashDeviceFault extends BaseWashDeviceFault<WashDeviceFault> {
	public static final WashDeviceFault dao = new WashDeviceFault().dao();
}
