package com.wash.model;

import com.wash.model.base.BaseWashWorkDeviceRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashWorkDeviceRecord extends BaseWashWorkDeviceRecord<WashWorkDeviceRecord> {
	public static final WashWorkDeviceRecord dao = new WashWorkDeviceRecord().dao();
}
