package com.wash.model;

import com.wash.model.base.BaseWashCoupon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashCoupon extends BaseWashCoupon<WashCoupon> {
	public static final WashCoupon dao = new WashCoupon().dao();
}
