package com.wash.model;

import com.wash.model.base.BaseWashDeviceCommandBack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashDeviceCommandBack extends BaseWashDeviceCommandBack<WashDeviceCommandBack> {
	public static final WashDeviceCommandBack dao = new WashDeviceCommandBack().dao();
}
