package com.wash.model;

import com.wash.model.base.BaseWashCarMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WashCarMember extends BaseWashCarMember<WashCarMember> {
	public static final WashCarMember dao = new WashCarMember().dao();
}
