package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTestLineWeatherMainCity<M extends BaseTestLineWeatherMainCity<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

	public M setDatestr(java.util.Date datestr) {
		set("datestr", datestr);
		return (M)this;
	}

	public java.util.Date getDatestr() {
		return get("datestr");
	}

	public M setBeijingMaxtemp(java.lang.Double beijingMaxtemp) {
		set("beijing_maxtemp", beijingMaxtemp);
		return (M)this;
	}

	public java.lang.Double getBeijingMaxtemp() {
		return get("beijing_maxtemp");
	}

	public M setBeijingMintemp(java.lang.Double beijingMintemp) {
		set("beijing_mintemp", beijingMintemp);
		return (M)this;
	}

	public java.lang.Double getBeijingMintemp() {
		return get("beijing_mintemp");
	}

	public M setChangchunMaxtemp(java.lang.Double changchunMaxtemp) {
		set("changchun_maxtemp", changchunMaxtemp);
		return (M)this;
	}

	public java.lang.Double getChangchunMaxtemp() {
		return get("changchun_maxtemp");
	}

	public M setChangchunMintemp(java.lang.Double changchunMintemp) {
		set("changchun_mintemp", changchunMintemp);
		return (M)this;
	}

	public java.lang.Double getChangchunMintemp() {
		return get("changchun_mintemp");
	}

	public M setShenyangMaxtemp(java.lang.Double shenyangMaxtemp) {
		set("shenyang_maxtemp", shenyangMaxtemp);
		return (M)this;
	}

	public java.lang.Double getShenyangMaxtemp() {
		return get("shenyang_maxtemp");
	}

	public M setShenyangMintemp(java.lang.Double shenyangMintemp) {
		set("shenyang_mintemp", shenyangMintemp);
		return (M)this;
	}

	public java.lang.Double getShenyangMintemp() {
		return get("shenyang_mintemp");
	}

	public M setHaerbinMaxtemp(java.lang.Double haerbinMaxtemp) {
		set("haerbin_maxtemp", haerbinMaxtemp);
		return (M)this;
	}

	public java.lang.Double getHaerbinMaxtemp() {
		return get("haerbin_maxtemp");
	}

	public M setHaerbinMintemp(java.lang.Double haerbinMintemp) {
		set("haerbin_mintemp", haerbinMintemp);
		return (M)this;
	}

	public java.lang.Double getHaerbinMintemp() {
		return get("haerbin_mintemp");
	}

}
