package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDkContractPay<M extends BaseDkContractPay<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setContractId(java.lang.String contractId) {
		set("contract_id", contractId);
		return (M)this;
	}

	public java.lang.String getContractId() {
		return get("contract_id");
	}

	public M setPayDate(java.util.Date payDate) {
		set("pay_date", payDate);
		return (M)this;
	}

	public java.util.Date getPayDate() {
		return get("pay_date");
	}

	public M setPayFee(java.math.BigDecimal payFee) {
		set("pay_fee", payFee);
		return (M)this;
	}

	public java.math.BigDecimal getPayFee() {
		return get("pay_fee");
	}

	public M setReviewStatus(java.lang.String reviewStatus) {
		set("review_status", reviewStatus);
		return (M)this;
	}

	public java.lang.String getReviewStatus() {
		return get("review_status");
	}

	public M setReviewBy(java.lang.String reviewBy) {
		set("review_by", reviewBy);
		return (M)this;
	}

	public java.lang.String getReviewBy() {
		return get("review_by");
	}

	public M setIsReview(java.lang.String isReview) {
		set("is_review", isReview);
		return (M)this;
	}

	public java.lang.String getIsReview() {
		return get("is_review");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
