package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashTbSequence<M extends BaseWashTbSequence<M>> extends Model<M> implements IBean {

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setCurrentValue(java.lang.Integer currentValue) {
		set("current_value", currentValue);
		return (M)this;
	}

	public java.lang.Integer getCurrentValue() {
		return get("current_value");
	}

	public M setIncrement(java.lang.Integer Increment) {
		set("_increment", Increment);
		return (M)this;
	}

	public java.lang.Integer getIncrement() {
		return get("_increment");
	}

}
