package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDkProduct<M extends BaseDkProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}

	public java.lang.String getModel() {
		return get("model");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setCostPrice(java.math.BigDecimal costPrice) {
		set("cost_price", costPrice);
		return (M)this;
	}

	public java.math.BigDecimal getCostPrice() {
		return get("cost_price");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public M setClassifyId(java.lang.String classifyId) {
		set("classify_id", classifyId);
		return (M)this;
	}

	public java.lang.String getClassifyId() {
		return get("classify_id");
	}

	public M setPower(java.lang.Integer power) {
		set("power", power);
		return (M)this;
	}

	public java.lang.Integer getPower() {
		return get("power");
	}

	public M setPlace(java.lang.String place) {
		set("place", place);
		return (M)this;
	}

	public java.lang.String getPlace() {
		return get("place");
	}

	public M setBrandId(java.lang.String brandId) {
		set("brand_id", brandId);
		return (M)this;
	}

	public java.lang.String getBrandId() {
		return get("brand_id");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public M setProductType(java.lang.String productType) {
		set("product_type", productType);
		return (M)this;
	}

	public java.lang.String getProductType() {
		return get("product_type");
	}

	public M setDescript(java.lang.String descript) {
		set("descript", descript);
		return (M)this;
	}

	public java.lang.String getDescript() {
		return get("descript");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
