package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGenTable<M extends BaseGenTable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setComments(java.lang.String comments) {
		set("comments", comments);
		return (M)this;
	}

	public java.lang.String getComments() {
		return get("comments");
	}

	public M setClassName(java.lang.String className) {
		set("class_name", className);
		return (M)this;
	}

	public java.lang.String getClassName() {
		return get("class_name");
	}

	public M setParentTable(java.lang.String parentTable) {
		set("parent_table", parentTable);
		return (M)this;
	}

	public java.lang.String getParentTable() {
		return get("parent_table");
	}

	public M setParentTableFk(java.lang.String parentTableFk) {
		set("parent_table_fk", parentTableFk);
		return (M)this;
	}

	public java.lang.String getParentTableFk() {
		return get("parent_table_fk");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

	public M setIssync(java.lang.String issync) {
		set("issync", issync);
		return (M)this;
	}

	public java.lang.String getIssync() {
		return get("issync");
	}

	public M setTableType(java.lang.String tableType) {
		set("table_type", tableType);
		return (M)this;
	}

	public java.lang.String getTableType() {
		return get("table_type");
	}

}
