package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashDeviceFault<M extends BaseWashDeviceFault<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setMac(java.lang.String mac) {
		set("mac", mac);
		return (M)this;
	}

	public java.lang.String getMac() {
		return get("mac");
	}

	public M setDeviceName(java.lang.String deviceName) {
		set("device_name", deviceName);
		return (M)this;
	}

	public java.lang.String getDeviceName() {
		return get("device_name");
	}

	public M setDeviceAddress(java.lang.String deviceAddress) {
		set("device_address", deviceAddress);
		return (M)this;
	}

	public java.lang.String getDeviceAddress() {
		return get("device_address");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setFaultTime(java.util.Date faultTime) {
		set("fault_time", faultTime);
		return (M)this;
	}

	public java.util.Date getFaultTime() {
		return get("fault_time");
	}

	public M setFaultDesc(java.lang.String faultDesc) {
		set("fault_desc", faultDesc);
		return (M)this;
	}

	public java.lang.String getFaultDesc() {
		return get("fault_desc");
	}

	public M setHandleTime(java.util.Date handleTime) {
		set("handle_time", handleTime);
		return (M)this;
	}

	public java.util.Date getHandleTime() {
		return get("handle_time");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
