package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSystemconfig<M extends BaseSystemconfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setSmtp(java.lang.String smtp) {
		set("smtp", smtp);
		return (M)this;
	}

	public java.lang.String getSmtp() {
		return get("smtp");
	}

	public M setPort(java.lang.String port) {
		set("port", port);
		return (M)this;
	}

	public java.lang.String getPort() {
		return get("port");
	}

	public M setMailname(java.lang.String mailname) {
		set("mailname", mailname);
		return (M)this;
	}

	public java.lang.String getMailname() {
		return get("mailname");
	}

	public M setMailpassword(java.lang.String mailpassword) {
		set("mailpassword", mailpassword);
		return (M)this;
	}

	public java.lang.String getMailpassword() {
		return get("mailpassword");
	}

	public M setSmsname(java.lang.String smsname) {
		set("smsname", smsname);
		return (M)this;
	}

	public java.lang.String getSmsname() {
		return get("smsname");
	}

	public M setSmspassword(java.lang.String smspassword) {
		set("smspassword", smspassword);
		return (M)this;
	}

	public java.lang.String getSmspassword() {
		return get("smspassword");
	}

}
