package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMonitor<M extends BaseMonitor<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setCpu(java.lang.String cpu) {
		set("cpu", cpu);
		return (M)this;
	}

	public java.lang.String getCpu() {
		return get("cpu");
	}

	public M setJvm(java.lang.String jvm) {
		set("jvm", jvm);
		return (M)this;
	}

	public java.lang.String getJvm() {
		return get("jvm");
	}

	public M setRam(java.lang.String ram) {
		set("ram", ram);
		return (M)this;
	}

	public java.lang.String getRam() {
		return get("ram");
	}

	public M setToemail(java.lang.String toemail) {
		set("toemail", toemail);
		return (M)this;
	}

	public java.lang.String getToemail() {
		return get("toemail");
	}

}
