package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDkContract<M extends BaseDkContract<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public M setContractFlag(java.lang.String contractFlag) {
		set("contract_flag", contractFlag);
		return (M)this;
	}

	public java.lang.String getContractFlag() {
		return get("contract_flag");
	}

	public M setQuotationId(java.lang.String quotationId) {
		set("quotation_id", quotationId);
		return (M)this;
	}

	public java.lang.String getQuotationId() {
		return get("quotation_id");
	}

	public M setContractNumber(java.lang.String contractNumber) {
		set("contract_number", contractNumber);
		return (M)this;
	}

	public java.lang.String getContractNumber() {
		return get("contract_number");
	}

	public M setMemberName(java.lang.String memberName) {
		set("member_name", memberName);
		return (M)this;
	}

	public java.lang.String getMemberName() {
		return get("member_name");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setMemberId(java.lang.String memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.String getMemberId() {
		return get("member_id");
	}

	public M setContractFee(java.math.BigDecimal contractFee) {
		set("contract_fee", contractFee);
		return (M)this;
	}

	public java.math.BigDecimal getContractFee() {
		return get("contract_fee");
	}

	public M setTotalFee(java.math.BigDecimal totalFee) {
		set("total_fee", totalFee);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFee() {
		return get("total_fee");
	}

	public M setArriveFee(java.math.BigDecimal arriveFee) {
		set("arrive_fee", arriveFee);
		return (M)this;
	}

	public java.math.BigDecimal getArriveFee() {
		return get("arrive_fee");
	}

	public M setConnectionRatio(java.math.BigDecimal connectionRatio) {
		set("connection_ratio", connectionRatio);
		return (M)this;
	}

	public java.math.BigDecimal getConnectionRatio() {
		return get("connection_ratio");
	}

	public M setInstallBy(java.lang.String installBy) {
		set("install_by", installBy);
		return (M)this;
	}

	public java.lang.String getInstallBy() {
		return get("install_by");
	}

	public M setSaleBy(java.lang.String saleBy) {
		set("sale_by", saleBy);
		return (M)this;
	}

	public java.lang.String getSaleBy() {
		return get("sale_by");
	}

	public M setSupervisionBy(java.lang.String supervisionBy) {
		set("supervision_by", supervisionBy);
		return (M)this;
	}

	public java.lang.String getSupervisionBy() {
		return get("supervision_by");
	}

	public M setProductType(java.lang.String productType) {
		set("product_type", productType);
		return (M)this;
	}

	public java.lang.String getProductType() {
		return get("product_type");
	}

	public M setContractStatus(java.lang.String contractStatus) {
		set("contract_status", contractStatus);
		return (M)this;
	}

	public java.lang.String getContractStatus() {
		return get("contract_status");
	}

	public M setReviewStatus(java.lang.String reviewStatus) {
		set("review_status", reviewStatus);
		return (M)this;
	}

	public java.lang.String getReviewStatus() {
		return get("review_status");
	}

	public M setReviewBy(java.lang.String reviewBy) {
		set("review_by", reviewBy);
		return (M)this;
	}

	public java.lang.String getReviewBy() {
		return get("review_by");
	}

	public M setReviewTime(java.util.Date reviewTime) {
		set("review_time", reviewTime);
		return (M)this;
	}

	public java.util.Date getReviewTime() {
		return get("review_time");
	}

	public M setIsReview(java.lang.String isReview) {
		set("is_review", isReview);
		return (M)this;
	}

	public java.lang.String getIsReview() {
		return get("is_review");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
