package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDkAuditRecord<M extends BaseDkAuditRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setRecordId(java.lang.String recordId) {
		set("record_id", recordId);
		return (M)this;
	}

	public java.lang.String getRecordId() {
		return get("record_id");
	}

	public M setRecordType(java.lang.String recordType) {
		set("record_type", recordType);
		return (M)this;
	}

	public java.lang.String getRecordType() {
		return get("record_type");
	}

	public M setReviewStatus(java.lang.String reviewStatus) {
		set("review_status", reviewStatus);
		return (M)this;
	}

	public java.lang.String getReviewStatus() {
		return get("review_status");
	}

	public M setReviewBy(java.lang.String reviewBy) {
		set("review_by", reviewBy);
		return (M)this;
	}

	public java.lang.String getReviewBy() {
		return get("review_by");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
