package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysRoleOffice<M extends BaseSysRoleOffice<M>> extends Model<M> implements IBean {

	public M setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public java.lang.String getRoleId() {
		return get("role_id");
	}

	public M setOfficeId(java.lang.String officeId) {
		set("office_id", officeId);
		return (M)this;
	}

	public java.lang.String getOfficeId() {
		return get("office_id");
	}

}
