package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGenScheme<M extends BaseGenScheme<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}

	public java.lang.String getCategory() {
		return get("category");
	}

	public M setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
		return (M)this;
	}

	public java.lang.String getPackageName() {
		return get("package_name");
	}

	public M setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
		return (M)this;
	}

	public java.lang.String getModuleName() {
		return get("module_name");
	}

	public M setSubModuleName(java.lang.String subModuleName) {
		set("sub_module_name", subModuleName);
		return (M)this;
	}

	public java.lang.String getSubModuleName() {
		return get("sub_module_name");
	}

	public M setFunctionName(java.lang.String functionName) {
		set("function_name", functionName);
		return (M)this;
	}

	public java.lang.String getFunctionName() {
		return get("function_name");
	}

	public M setFunctionNameSimple(java.lang.String functionNameSimple) {
		set("function_name_simple", functionNameSimple);
		return (M)this;
	}

	public java.lang.String getFunctionNameSimple() {
		return get("function_name_simple");
	}

	public M setFunctionAuthor(java.lang.String functionAuthor) {
		set("function_author", functionAuthor);
		return (M)this;
	}

	public java.lang.String getFunctionAuthor() {
		return get("function_author");
	}

	public M setGenTableId(java.lang.String genTableId) {
		set("gen_table_id", genTableId);
		return (M)this;
	}

	public java.lang.String getGenTableId() {
		return get("gen_table_id");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
