package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashOrdOrder<M extends BaseWashOrdOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public M setCarPersonId(java.lang.String carPersonId) {
		set("car_person_id", carPersonId);
		return (M)this;
	}

	public java.lang.String getCarPersonId() {
		return get("car_person_id");
	}

	public M setCarNumber(java.lang.String carNumber) {
		set("car_number", carNumber);
		return (M)this;
	}

	public java.lang.String getCarNumber() {
		return get("car_number");
	}

	public M setWashPersonId(java.lang.String washPersonId) {
		set("wash_person_id", washPersonId);
		return (M)this;
	}

	public java.lang.String getWashPersonId() {
		return get("wash_person_id");
	}

	public M setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
		return (M)this;
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public M setDeviceMac(java.lang.String deviceMac) {
		set("device_mac", deviceMac);
		return (M)this;
	}

	public java.lang.String getDeviceMac() {
		return get("device_mac");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public M setSetMealId(java.lang.String setMealId) {
		set("set_meal_id", setMealId);
		return (M)this;
	}

	public java.lang.String getSetMealId() {
		return get("set_meal_id");
	}

	public M setTotalFee(java.math.BigDecimal totalFee) {
		set("total_fee", totalFee);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFee() {
		return get("total_fee");
	}

	public M setDiscountFee(java.math.BigDecimal discountFee) {
		set("discount_fee", discountFee);
		return (M)this;
	}

	public java.math.BigDecimal getDiscountFee() {
		return get("discount_fee");
	}

	public M setRealFee(java.math.BigDecimal realFee) {
		set("real_fee", realFee);
		return (M)this;
	}

	public java.math.BigDecimal getRealFee() {
		return get("real_fee");
	}

	public M setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
		return (M)this;
	}

	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setOrderStatus(java.lang.String orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}

	public java.lang.String getOrderStatus() {
		return get("order_status");
	}

	public M setPayMode(java.lang.String payMode) {
		set("pay_mode", payMode);
		return (M)this;
	}

	public java.lang.String getPayMode() {
		return get("pay_mode");
	}

	public M setPaySerialNumber(java.lang.String paySerialNumber) {
		set("pay_serial_number", paySerialNumber);
		return (M)this;
	}

	public java.lang.String getPaySerialNumber() {
		return get("pay_serial_number");
	}

	public M setWashFee(java.math.BigDecimal washFee) {
		set("wash_fee", washFee);
		return (M)this;
	}

	public java.math.BigDecimal getWashFee() {
		return get("wash_fee");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
