package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setCompanyId(java.lang.String companyId) {
		set("company_id", companyId);
		return (M)this;
	}

	public java.lang.String getCompanyId() {
		return get("company_id");
	}

	public M setOfficeId(java.lang.String officeId) {
		set("office_id", officeId);
		return (M)this;
	}

	public java.lang.String getOfficeId() {
		return get("office_id");
	}

	public M setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
		return (M)this;
	}

	public java.lang.String getLoginName() {
		return get("login_name");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setNo(java.lang.String no) {
		set("no", no);
		return (M)this;
	}

	public java.lang.String getNo() {
		return get("no");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public M setUserType(java.lang.String userType) {
		set("user_type", userType);
		return (M)this;
	}

	public java.lang.String getUserType() {
		return get("user_type");
	}

	public M setSign(java.lang.String sign) {
		set("sign", sign);
		return (M)this;
	}

	public java.lang.String getSign() {
		return get("sign");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}

	public java.lang.String getPhoto() {
		return get("photo");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}

	public java.lang.String getLoginIp() {
		return get("login_ip");
	}

	public M setLoginDate(java.util.Date loginDate) {
		set("login_date", loginDate);
		return (M)this;
	}

	public java.util.Date getLoginDate() {
		return get("login_date");
	}

	public M setLoginFlag(java.lang.String loginFlag) {
		set("login_flag", loginFlag);
		return (M)this;
	}

	public java.lang.String getLoginFlag() {
		return get("login_flag");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

	public M setQrcode(java.lang.String qrcode) {
		set("qrcode", qrcode);
		return (M)this;
	}

	public java.lang.String getQrcode() {
		return get("qrcode");
	}

}
