package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashCoupon<M extends BaseWashCoupon<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setFlag(java.lang.String flag) {
		set("flag", flag);
		return (M)this;
	}

	public java.lang.String getFlag() {
		return get("flag");
	}

	public M setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
		return (M)this;
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public M setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
		return (M)this;
	}

	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	public M setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
		return (M)this;
	}

	public java.math.BigDecimal getDiscountAmount() {
		return get("discount_amount");
	}

	public M setEffectiveTime(java.util.Date effectiveTime) {
		set("effective_time", effectiveTime);
		return (M)this;
	}

	public java.util.Date getEffectiveTime() {
		return get("effective_time");
	}

	public M setFailureTime(java.util.Date failureTime) {
		set("failure_time", failureTime);
		return (M)this;
	}

	public java.util.Date getFailureTime() {
		return get("failure_time");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
