package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOffice<M extends BaseSysOffice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public M setParentIds(java.lang.String parentIds) {
		set("parent_ids", parentIds);
		return (M)this;
	}

	public java.lang.String getParentIds() {
		return get("parent_ids");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSort(java.math.BigDecimal sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.math.BigDecimal getSort() {
		return get("sort");
	}

	public M setAreaId(java.lang.String areaId) {
		set("area_id", areaId);
		return (M)this;
	}

	public java.lang.String getAreaId() {
		return get("area_id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setGrade(java.lang.String grade) {
		set("grade", grade);
		return (M)this;
	}

	public java.lang.String getGrade() {
		return get("grade");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
		return (M)this;
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public M setMaster(java.lang.String master) {
		set("master", master);
		return (M)this;
	}

	public java.lang.String getMaster() {
		return get("master");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setFax(java.lang.String fax) {
		set("fax", fax);
		return (M)this;
	}

	public java.lang.String getFax() {
		return get("fax");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setUSEABLE(java.lang.String USEABLE) {
		set("USEABLE", USEABLE);
		return (M)this;
	}

	public java.lang.String getUSEABLE() {
		return get("USEABLE");
	}

	public M setPrimaryPerson(java.lang.String primaryPerson) {
		set("PRIMARY_PERSON", primaryPerson);
		return (M)this;
	}

	public java.lang.String getPrimaryPerson() {
		return get("PRIMARY_PERSON");
	}

	public M setDeputyPerson(java.lang.String deputyPerson) {
		set("DEPUTY_PERSON", deputyPerson);
		return (M)this;
	}

	public java.lang.String getDeputyPerson() {
		return get("DEPUTY_PERSON");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
