package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashTFlow<M extends BaseWashTFlow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setTSn(java.lang.String tSn) {
		set("t_sn", tSn);
		return (M)this;
	}

	public java.lang.String getTSn() {
		return get("t_sn");
	}

	public M setTDatetime(java.util.Date tDatetime) {
		set("t_datetime", tDatetime);
		return (M)this;
	}

	public java.util.Date getTDatetime() {
		return get("t_datetime");
	}

	public M setTType(java.lang.String tType) {
		set("t_type", tType);
		return (M)this;
	}

	public java.lang.String getTType() {
		return get("t_type");
	}

	public M setMemberId(java.lang.String memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.String getMemberId() {
		return get("member_id");
	}

	public M setTppType(java.lang.Integer tppType) {
		set("tpp_type", tppType);
		return (M)this;
	}

	public java.lang.Integer getTppType() {
		return get("tpp_type");
	}

	public M setComment(java.lang.String comment) {
		set("comment", comment);
		return (M)this;
	}

	public java.lang.String getComment() {
		return get("comment");
	}

	public M setTAmount(java.math.BigDecimal tAmount) {
		set("t_amount", tAmount);
		return (M)this;
	}

	public java.math.BigDecimal getTAmount() {
		return get("t_amount");
	}

	public M setTppSn(java.lang.String tppSn) {
		set("tpp_sn", tppSn);
		return (M)this;
	}

	public java.lang.String getTppSn() {
		return get("tpp_sn");
	}

	public M setTppResult(java.lang.Integer tppResult) {
		set("tpp_result", tppResult);
		return (M)this;
	}

	public java.lang.Integer getTppResult() {
		return get("tpp_result");
	}

}
