package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCalendar<M extends BaseCalendar<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setStarttime(java.lang.String starttime) {
		set("starttime", starttime);
		return (M)this;
	}

	public java.lang.String getStarttime() {
		return get("starttime");
	}

	public M setEndtime(java.lang.String endtime) {
		set("endtime", endtime);
		return (M)this;
	}

	public java.lang.String getEndtime() {
		return get("endtime");
	}

	public M setAllday(java.lang.String allday) {
		set("allday", allday);
		return (M)this;
	}

	public java.lang.String getAllday() {
		return get("allday");
	}

	public M setColor(java.lang.String color) {
		set("color", color);
		return (M)this;
	}

	public java.lang.String getColor() {
		return get("color");
	}

	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

}
