package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashOrdSetMeal<M extends BaseWashOrdSetMeal<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}

	public java.lang.String getOrderId() {
		return get("order_id");
	}

	public M setSetMealId(java.lang.String setMealId) {
		set("set_meal_id", setMealId);
		return (M)this;
	}

	public java.lang.String getSetMealId() {
		return get("set_meal_id");
	}

	public M setNAME(java.lang.String NAME) {
		set("NAME", NAME);
		return (M)this;
	}

	public java.lang.String getNAME() {
		return get("NAME");
	}

	public M setSummary(java.lang.String summary) {
		set("summary", summary);
		return (M)this;
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
		return (M)this;
	}

	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public M setSalePrice(java.math.BigDecimal salePrice) {
		set("sale_price", salePrice);
		return (M)this;
	}

	public java.math.BigDecimal getSalePrice() {
		return get("sale_price");
	}

	public M setDuration(java.lang.String duration) {
		set("duration", duration);
		return (M)this;
	}

	public java.lang.String getDuration() {
		return get("duration");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
