package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUserFriend<M extends BaseSysUserFriend<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public M setFriendId(java.lang.String friendId) {
		set("friendId", friendId);
		return (M)this;
	}

	public java.lang.String getFriendId() {
		return get("friendId");
	}

}
