package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseIimMail<M extends BaseIimMail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setOverview(java.lang.String overview) {
		set("overview", overview);
		return (M)this;
	}

	public java.lang.String getOverview() {
		return get("overview");
	}

	public M setContent(byte[] content) {
		set("content", content);
		return (M)this;
	}

	public byte[] getContent() {
		return get("content");
	}

}
