package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setRemoteAddr(java.lang.String remoteAddr) {
		set("remote_addr", remoteAddr);
		return (M)this;
	}

	public java.lang.String getRemoteAddr() {
		return get("remote_addr");
	}

	public M setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
		return (M)this;
	}

	public java.lang.String getUserAgent() {
		return get("user_agent");
	}

	public M setRequestUri(java.lang.String requestUri) {
		set("request_uri", requestUri);
		return (M)this;
	}

	public java.lang.String getRequestUri() {
		return get("request_uri");
	}

	public M setMethod(java.lang.String method) {
		set("method", method);
		return (M)this;
	}

	public java.lang.String getMethod() {
		return get("method");
	}

	public M setParams(java.lang.String params) {
		set("params", params);
		return (M)this;
	}

	public java.lang.String getParams() {
		return get("params");
	}

	public M setException(java.lang.String exception) {
		set("exception", exception);
		return (M)this;
	}

	public java.lang.String getException() {
		return get("exception");
	}

}
