package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashDeviceHeart<M extends BaseWashDeviceHeart<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setMac(java.lang.String mac) {
		set("mac", mac);
		return (M)this;
	}

	public java.lang.String getMac() {
		return get("mac");
	}

	public M setOperatorTime(java.util.Date operatorTime) {
		set("operator_time", operatorTime);
		return (M)this;
	}

	public java.util.Date getOperatorTime() {
		return get("operator_time");
	}

}
