package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWashCouponDetail<M extends BaseWashCouponDetail<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setCouponId(java.lang.String couponId) {
		set("coupon_id", couponId);
		return (M)this;
	}

	public java.lang.String getCouponId() {
		return get("coupon_id");
	}

	public M setCouponNo(java.lang.String couponNo) {
		set("coupon_no", couponNo);
		return (M)this;
	}

	public java.lang.String getCouponNo() {
		return get("coupon_no");
	}

	public M setCouponName(java.lang.String couponName) {
		set("coupon_name", couponName);
		return (M)this;
	}

	public java.lang.String getCouponName() {
		return get("coupon_name");
	}

	public M setFlag(java.lang.String flag) {
		set("flag", flag);
		return (M)this;
	}

	public java.lang.String getFlag() {
		return get("flag");
	}

	public M setMemberId(java.lang.String memberId) {
		set("member_id", memberId);
		return (M)this;
	}

	public java.lang.String getMemberId() {
		return get("member_id");
	}

	public M setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
		return (M)this;
	}

	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	public M setDiscountAmount(java.math.BigDecimal discountAmount) {
		set("discount_amount", discountAmount);
		return (M)this;
	}

	public java.math.BigDecimal getDiscountAmount() {
		return get("discount_amount");
	}

	public M setEffectiveTime(java.util.Date effectiveTime) {
		set("effective_time", effectiveTime);
		return (M)this;
	}

	public java.util.Date getEffectiveTime() {
		return get("effective_time");
	}

	public M setFailureTime(java.util.Date failureTime) {
		set("failure_time", failureTime);
		return (M)this;
	}

	public java.util.Date getFailureTime() {
		return get("failure_time");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setOrderNo(java.lang.String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}

	public java.lang.String getOrderNo() {
		return get("order_no");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

}
