package com.wash.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGenTableColumn<M extends BaseGenTableColumn<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setGenTableId(java.lang.String genTableId) {
		set("gen_table_id", genTableId);
		return (M)this;
	}

	public java.lang.String getGenTableId() {
		return get("gen_table_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setComments(java.lang.String comments) {
		set("comments", comments);
		return (M)this;
	}

	public java.lang.String getComments() {
		return get("comments");
	}

	public M setJdbcType(java.lang.String jdbcType) {
		set("jdbc_type", jdbcType);
		return (M)this;
	}

	public java.lang.String getJdbcType() {
		return get("jdbc_type");
	}

	public M setJavaType(java.lang.String javaType) {
		set("java_type", javaType);
		return (M)this;
	}

	public java.lang.String getJavaType() {
		return get("java_type");
	}

	public M setJavaField(java.lang.String javaField) {
		set("java_field", javaField);
		return (M)this;
	}

	public java.lang.String getJavaField() {
		return get("java_field");
	}

	public M setIsPk(java.lang.String isPk) {
		set("is_pk", isPk);
		return (M)this;
	}

	public java.lang.String getIsPk() {
		return get("is_pk");
	}

	public M setIsNull(java.lang.String isNull) {
		set("is_null", isNull);
		return (M)this;
	}

	public java.lang.String getIsNull() {
		return get("is_null");
	}

	public M setIsInsert(java.lang.String isInsert) {
		set("is_insert", isInsert);
		return (M)this;
	}

	public java.lang.String getIsInsert() {
		return get("is_insert");
	}

	public M setIsEdit(java.lang.String isEdit) {
		set("is_edit", isEdit);
		return (M)this;
	}

	public java.lang.String getIsEdit() {
		return get("is_edit");
	}

	public M setIsList(java.lang.String isList) {
		set("is_list", isList);
		return (M)this;
	}

	public java.lang.String getIsList() {
		return get("is_list");
	}

	public M setIsQuery(java.lang.String isQuery) {
		set("is_query", isQuery);
		return (M)this;
	}

	public java.lang.String getIsQuery() {
		return get("is_query");
	}

	public M setQueryType(java.lang.String queryType) {
		set("query_type", queryType);
		return (M)this;
	}

	public java.lang.String getQueryType() {
		return get("query_type");
	}

	public M setShowType(java.lang.String showType) {
		set("show_type", showType);
		return (M)this;
	}

	public java.lang.String getShowType() {
		return get("show_type");
	}

	public M setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
		return (M)this;
	}

	public java.lang.String getDictType() {
		return get("dict_type");
	}

	public M setSettings(java.lang.String settings) {
		set("settings", settings);
		return (M)this;
	}

	public java.lang.String getSettings() {
		return get("settings");
	}

	public M setSort(java.math.BigDecimal sort) {
		set("sort", sort);
		return (M)this;
	}

	public java.math.BigDecimal getSort() {
		return get("sort");
	}

	public M setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
		return (M)this;
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
		return (M)this;
	}

	public java.lang.String getUpdateBy() {
		return get("update_by");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public M setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public M setDelFlag(java.lang.String delFlag) {
		set("del_flag", delFlag);
		return (M)this;
	}

	public java.lang.String getDelFlag() {
		return get("del_flag");
	}

	public M setIsForm(java.lang.String isForm) {
		set("is_form", isForm);
		return (M)this;
	}

	public java.lang.String getIsForm() {
		return get("is_form");
	}

	public M setTableName(java.lang.String tableName) {
		set("tableName", tableName);
		return (M)this;
	}

	public java.lang.String getTableName() {
		return get("tableName");
	}

	public M setFieldLabels(java.lang.String fieldLabels) {
		set("fieldLabels", fieldLabels);
		return (M)this;
	}

	public java.lang.String getFieldLabels() {
		return get("fieldLabels");
	}

	public M setFieldKeys(java.lang.String fieldKeys) {
		set("fieldKeys", fieldKeys);
		return (M)this;
	}

	public java.lang.String getFieldKeys() {
		return get("fieldKeys");
	}

	public M setSearchLabel(java.lang.String searchLabel) {
		set("searchLabel", searchLabel);
		return (M)this;
	}

	public java.lang.String getSearchLabel() {
		return get("searchLabel");
	}

	public M setSearchKey(java.lang.String searchKey) {
		set("searchKey", searchKey);
		return (M)this;
	}

	public java.lang.String getSearchKey() {
		return get("searchKey");
	}

	public M setValidateType(java.lang.String validateType) {
		set("validateType", validateType);
		return (M)this;
	}

	public java.lang.String getValidateType() {
		return get("validateType");
	}

	public M setMinLength(java.lang.String minLength) {
		set("min_length", minLength);
		return (M)this;
	}

	public java.lang.String getMinLength() {
		return get("min_length");
	}

	public M setMaxLength(java.lang.String maxLength) {
		set("max_length", maxLength);
		return (M)this;
	}

	public java.lang.String getMaxLength() {
		return get("max_length");
	}

	public M setMinValue(java.lang.String minValue) {
		set("min_value", minValue);
		return (M)this;
	}

	public java.lang.String getMinValue() {
		return get("min_value");
	}

	public M setMaxValue(java.lang.String maxValue) {
		set("max_value", maxValue);
		return (M)this;
	}

	public java.lang.String getMaxValue() {
		return get("max_value");
	}

}
